export const WORDS = [
  'spine',
  'nasal',
   'polyp',
    'skull',
     'thigh',
      'mouth',
       'nurse',
        'admin',
         'medic',
          'actue',
           'spine',
            'gland',
             'sperm',
              'mucus',
               'cysts',
                'distal',
                 'fossa',
                  'renal',
                   'urine',
                    'stool',
                    'stoma',
                    'acute',
 'adult', 'alter', 'array', 'assay', 'audit', 'brief', 'chart', 'cycle', 'digit', 'donor', 'entry', 'equip', 'fluid', 'gland', 'graft', 'graph', 'hence', 'index', 'inner', 'issue', 'label', 'laser', 'layer', 'lipid', 'liver', 'major', 'minor', 'mount', 'novel', 'occur', 'onset', 'oxide', 'panel', 'phase', 'prior', 'probe', 'range', 'ratio', 'react', 'renal', 'route', 'score', 'serum', 'shift', 'toxic', 'trace', 'tract', 'trend', 'tumor', 'urban', 'valid', 'virus', 'vital',]
